Test stack version

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -43,29 +43,36 @@ mkdir -p $BUILD_DIR
 mkdir -p $CACHE_DIR
 
 # fix STACK variable if unset
-if [ -z "${STACK}" ];
+# read in R version if file exists
+if [[ -f "$BUILD_DIR/.stack-version" ]];
 then
-  STACK="cedar-14"
-fi
+  STACK=`read_var $BUILD_DIR/.stack-version`
+  echo "NOTE: Using Stack version override [$STACK]" | indent
+else
+  if [ -z "${STACK}" ];
+  then
+    STACK="cedar-14"
+  fi
 
 # ensure correct stack
-if [[ ! "$STACK" == "cedar-14" ]]; then
+  if [[ ! "$STACK" == "cedar-14" ]]; then
 
-  echo
-  echo "-----> ERROR: This version of the buildpack is intended for use with the 'cedar-14' stack"
-  echo
-  echo "       Use the 'heroku stack:set' CLI command to use the 'cedar-14' stack."
-  echo "       See https://devcenter.heroku.com/articles/stack for more information."
-  echo
-  exit 1
+    echo
+    echo "-----> ERROR: This version of the buildpack is intended for use with the 'cedar-14' stack"
+    echo
+    echo "       Use the 'heroku stack:set' CLI command to use the 'cedar-14' stack."
+    echo "       See https://devcenter.heroku.com/articles/stack for more information."
+    echo
+    exit 1
 
+  fi
 fi
 
 # show deprecation notice
-echo
-topic "WARNING: This version of the buildpack is no longer supported."
-echo "Please see https://github.com/virtualstaticvoid/heroku-buildpack-r for more information." | indent
-echo
+#echo
+#topic "WARNING: This version of the buildpack is no longer supported."
+#echo "Please see https://github.com/virtualstaticvoid/heroku-buildpack-r for more information." | indent
+#echo
 
 # config
 VENDOR_DIR="$BUILD_DIR/vendor"
